sudo: required
services:
  - docker

before_install:
  - docker build -t bindabernardo/docker-react -f Dockerfile.dev .

#commands to run
script:
  - docker run -e CI=true bindabernardo/docker-react npm run test -- --coverage
  